version: '3'
services:
  rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
